# Generated by Django 3.1.7 on 2021-05-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20210510_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Fecha_publicacion',
        ),
    ]
