# Generated by Django 3.1.7 on 2021-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
