# Generated by Django 3.1.7 on 2021-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
    ]
