# Generated by Django 3.1.7 on 2021-05-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20210510_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libros.category'),
        ),
    ]
