# Generated by Django 3.2 on 2021-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0010_auto_20210518_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(to='libros.Category'),
        ),
    ]
