# Generated by Django 3.2 on 2021-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0012_auto_20210707_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(choices=[('Español', 'Español')], default='Español', max_length=60),
        ),
    ]
