# Generated by Django 3.2 on 2021-07-23 15:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0013_alter_libro_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='portada',
        ),
        migrations.AddField(
            model_name='libro',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
