# Generated by Django 3.2 on 2021-07-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0014_auto_20210723_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='image',
            new_name='portada',
        ),
    ]
