# Generated by Django 3.1.7 on 2021-05-12 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0007_auto_20210512_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.libro')),
            ],
        ),
    ]
