# Generated by Django 3.2 on 2021-05-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0002_auto_20210512_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compras',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_detalle', to='compras.compras'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
