# Generated by Django 3.2 on 2021-05-21 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0011_auto_20210519_1537'),
        ('compras', '0005_auto_20210518_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='total',
        ),
        migrations.AddField(
            model_name='compras',
            name='cancelado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='compras',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Productos'),
        ),
        migrations.AddField(
            model_name='compras',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='compras',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='compras',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=9, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
