# Generated by Django 3.2 on 2021-05-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_carrito_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='codigo',
        ),
    ]
