# Generated by Django 3.2 on 2021-05-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_carrito_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='total',
        ),
    ]
