# Generated by Django 3.2 on 2021-05-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0007_alter_tarjeta_id'),
        ('compras', '0011_remove_detallecompra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarjetas.tarjeta'),
        ),
    ]
