# Generated by Django 3.2 on 2021-05-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_devolucionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cancelado',
            field=models.CharField(blank=True, default='Aprobada', max_length=30),
        ),
    ]
