# Generated by Django 3.1.7 on 2021-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cvv', models.PositiveIntegerField(max_length=3)),
            ],
        ),
    ]
