# Generated by Django 3.1.7 on 2021-05-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.TextField(),
        ),
    ]
