# Generated by Django 3.1.7 on 2021-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_tarjeta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='saldo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
