# Generated by Django 3.2 on 2021-05-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0006_auto_20210518_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
