# Generated by Django 3.2 on 2021-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0008_alter_tarjeta_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='franquicia',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('AMERICAN EXPRESS', 'AMEX')], default='VISA', max_length=60),
        ),
    ]
