# Generated by Django 3.2 on 2021-07-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0009_tarjeta_franquicia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='franquicia',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('AMEX', 'AMERICAN EXPRESS')], default='VISA', max_length=60),
        ),
    ]
