# Generated by Django 3.1.7 on 2021-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('users', '0004_auto_20210422_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.ManyToManyField(to='libros.Category'),
        ),
    ]
