# Generated by Django 3.1.7 on 2021-04-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('users', '0005_user_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='libros.Category'),
        ),
    ]
