# Generated by Django 3.1.7 on 2021-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, choices=[('Balboa', 'Balboa'), ('Pereira', 'Pereira'), ('La virginia', 'La virginia')], default='Pereira', max_length=60, null=True),
        ),
    ]
