# Generated by Django 3.2.4 on 2021-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
