# Generated by Django 3.1.7 on 2021-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0009_auto_20210518_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'reservado'), ('cancelado', 'cancelado')], default='reservado', max_length=11)),
                ('libros', models.ManyToManyField(to='libros.Libro')),
            ],
        ),
    ]
