# Generated by Django 3.1.7 on 2021-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20210518_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
