# Generated by Django 3.1.7 on 2021-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reservas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
